config/routes.rb
Pizza::Application.routes.draw do
  
  # get "password_resets/new"

  # get  'signup', to: 'users#new',        as: 'signup'
  
  get  'login',  to: 'sessions#new',     as: 'login'
  post 'login',  to: 'sessions#create',  as: 'login'
  get  'logout', to: 'sessions#destroy', as: 'logout'
  get  'sessions', to: 'sessions#index', as: 'sessions'
  post 'sessions', to: 'sessions#create'
  # resources :sessions
  
  resources :users, except: [:new]
  resources :password_resets

  get 'weeks',     to: 'weeks#index', as: 'weeks'
  get 'weeks/:id', to: 'weeks#show',  as: 'week'

  get    'unread', to: 'notifications#index',   as: 'notifications'
  delete 'unread', to: 'notifications#destroy', as: 'notifications'

  get 'search', to: 'searches#index'
  resources :searches
  
  post 'announcements/markallread', to: 'announcements#markallread', as: 'mark_all_read'
  resources :announcements, except: [:show, :new, :edit]


  resources :school_days do
    resources :comments
  end


  resources :lectures do
    resources :comments
  end
  get 'lectures/new/preview',      to: 'lectures#new_preview',  as: 'new_lecture_preview'
  get 'lectures/:id/preview',      to: 'lectures#preview',      as: 'lecture_preview'
  get 'lectures/:id/edit/preview', to: 'lectures#edit_preview', as: 'edit_lecture_preview'


  resources :todos do
    resources :comments
  end
  get 'todos/new/preview',      to: 'todos#new_preview',  as: 'new_todo_preview'
  get 'todos/:id/preview',      to: 'todos#preview',      as: 'todo_preview'
  get 'todos/:id/edit/preview', to: 'todos#edit_preview', as: 'edit_todo_preview'
  

  resources :potds do
    resources :comments
  end
  get 'potds/new/preview',      to: 'potds#new_preview',  as: 'new_potd_preview'
  get 'potds/:id/preview',      to: 'potds#preview',      as: 'potd_preview'
  get 'potds/:id/edit/preview', to: 'potds#edit_preview', as: 'edit_potd_preview'


  resources :labs do
    resources :comments
  end
  get 'labs/new/preview',      to: 'labs#new_preview',  as: 'new_lab_preview'
  get 'labs/:id/preview',      to: 'labs#preview',      as: 'lab_preview'
  get 'labs/:id/edit/preview', to: 'labs#edit_preview', as: 'edit_lab_preview'


  resources :links do
    resources :comments
  end
  get 'links/new/preview',      to: 'links#new_preview',  as: 'new_link_preview'
  get 'links/:id/preview',      to: 'links#preview',      as: 'link_preview'
  get 'links/:id/edit/preview', to: 'links#edit_preview', as: 'edit_link_preview'


  resources :homeworks do
    resources :comments
  end
  get 'homeworks/new/preview',      to: 'homeworks#new_preview',  as: 'new_homework_preview'
  get 'homeworks/:id/preview',      to: 'homeworks#preview',      as: 'homework_preview'
  get 'homeworks/:id/edit/preview', to: 'homeworks#edit_preview', as: 'edit_homework_preview'
  

  resources :comments, only: [:index, :create, :update, :destroy]
  get 'discussion', to: 'comments#index', as: 'discussion'

  resources :attachments

  root :to => 'passthrough#index'

end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  # GET /weeks
  # GET /weeks.json
  def index
    @weeks = SchoolDay.select("week").map(&:week).sort.uniq

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weeks }
    end
  end

  # GET /weeks/1
  # GET /weeks/1.json
  def show
    @week = SchoolDay.where("week = ?", params[:id])

    @first_day_of_week = @week.sort_by(&:calendar_date).first.calendar_date.beginning_of_week
    @last_day_of_week  = @week.sort_by(&:calendar_date).first.calendar_date.end_of_week

    @prev_week = SchoolDay.where("week = ?", params[:id].to_i - 1)
    @next_week = SchoolDay.where("week = ?", params[:id].to_i + 1)
    @prev_week_id = params[:id].to_i - 1 unless @prev_week.empty?
    @next_week_id = params[:id].to_i + 1 unless @next_week.empty?

    respond_to do |format|
      format.html # show.html.erb
      format.json {  }
    end
  end

end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/index.html.erb
<div class="page-head">
  <% title "All Weeks" %>
  <h2 class="inline"><%= yield(:title) %></h2>
  
  <ul class="horizontal-list breadcrumb">
    <li>Show All: </li>
    <% material_type_list.each do |material_type_hash| %>
      <% material_type = material_type_hash[:name] %>
      <% material_icon = material_type_hash[:icon] %>

      <% material_types  = material_type.pluralize %>
      <% material_title  = material_capitalize(material_type) %>
      <% material_titles = material_title.pluralize %>
      
      <%# unless material_type == chosen_material_type %>
      <li>
        <a href="<%= self.send("#{material_types}_path") %>">
          <i class="icon-<%= material_icon %>"></i>
          <%= material_titles %>
        </a>
      </li>
      <%# end %>
      
    <% end %>
  </ul>
</div>

<div class="matter">
  <div class="container-fluid">
    <%= render "layouts/messages" %>
    <div class="row-fluid fit-content">

      <table class="table table-hover" id="linksTable" class="day-index" style="width:30%;">
        <thead>
          <tr>
            <th colspan="1" data-sort="int">Week</th>
            <th>Dates</th>
          </tr>
        </thead>
        <tbody>
          <% @weeks.each do |week| %>
            <% if (SchoolDay.where("week = ?", week).order("week").first.calendar_date <= Date.today) || (can? :update, @active_school_day) %>
            <% first_date = SchoolDay.where("week = ?", week).order("week").first.calendar_date %>
            <% first_day_of_week = first_date.beginning_of_week %>
            <% last_day_of_week  = first_date.end_of_week %>
            <% row_today = Date.today.between?(first_day_of_week, last_day_of_week) ? "warning" : "" %>
            <tr class="<%= row_today %>">
              <td>
                <h2><%= link_to week, week_path(week) %></h2>
              </td>
              <td>
                
                <%= link_to "#{first_day_of_week.strftime('%b %d')} - #{last_day_of_week.strftime('%b %d')}", week_path(week) %>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>

    </div>  
  </div>
</div>

<br />

app/views/weeks/show.html.erb
<div class="page-head">
  <% title "Week #{params[:id]}" %>
  <h2 class="inline"><%= yield(:title) %></h2>
  <h4><%= "#{@first_day_of_week.strftime("%b %d")} - #{@last_day_of_week.strftime("%b %d")}" %></h4>
  
  <ul class="breadcrumb">
    <li>
      <a href="#">Semester 002 </a> 

      <span class="divider">/</span>
    </li>

    <li class="dropdown">
      <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
        Week <%= params[:id] %>
        <i class = "caret"></i>
      </a>

      <ul class="dropdown-menu" role="menu">
        <% weeks = SchoolDay.select("week").map(&:week).uniq %>
        <% weeks.each do |week| %>
          <% if (SchoolDay.where("week = ?", week).order("week").first.calendar_date <= Date.today) || (can? :update, @active_school_day) %>
            <li>
              <%= link_to "Week #{week}", week_path(week) %>
            </li>
          <% end %>
        <% end %>
        <li><%= link_to "Show All Weeks", weeks_path %></li>
      </ul>
    </li>
  </ul>

  <ul class="breadcrumb">
    <%= link_to '<i class="icon-caret-left"></i> Prev Week'.html_safe, week_path(@prev_week_id) if @prev_week_id %>
    &nbsp;
    <% if @next_week_id %> 
      <%= link_to 'Next Week <i class="icon-caret-right"></i>'.html_safe, week_path(@next_week_id) if (@next_week.sort_by(&:calendar_date).first.calendar_date <= Date.today) || (can? :update, @active_school_day)  %>
    <% end %>
  </ul>

</div>

<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>

    <div class="row-fluid fit-content">

      <table class="table table-hover" id="linksTable" class="day-index">
        <thead>
          <tr>
            <th>Weekday</th>
            <th colspan="1" data-sort="int">Day</th>
            <th data-sort="date">Date</th>
            <th >Schedule</th>
            <th data-sort="string"><%= link_to 'Lectures',   lectures_path %></th>
            <th data-sort="string"><%= link_to 'To-Dos',     todos_path %></th>
            <th data-sort="string"><%= link_to 'POTD',       potds_path %></th>
            <th data-sort="string"><%= link_to 'Labs',       labs_path %></th>
            <th data-sort="string"><%= link_to 'Links',      links_path %></th>
            <th data-sort="string"><%= link_to 'Homeworks',  homeworks_path %></th>
          </tr>
        </thead>
        <tbody>
          <% @week.sort_by(&:ordinal).each do |school_day| %>
            <% if (school_day.calendar_date <= Date.today) || (can? :edit, school_day) %>
            <% row_today = school_day.calendar_date==Date.today ? "warning" : "" %>
            <tr class="<%= row_today %>">
              <td><h3><%= school_day.calendar_date.strftime("%a") %></h3></td>

              <td>
                <h3><%= link_to school_day.ordinal, school_day %></h3>
                <% if can? :edit, school_day %>
                  <%= link_to 'Edit', edit_school_day_path(school_day) %>
                  <%= link_to 'Delete', school_day, method: :delete, data: { confirm: 'Are you sure you want to delete this day? Resources associated with this day will not be deleted.' } %>
                <% end %>
              </td>

              <td>
                <%= school_day.calendar_date.strftime("%b %d, %Y")%>
              </td>
              <td>
                <%= simple_format(re_truncate school_day.schedule, length: 150) %>
              </td>
              <td>
                <ul class="no-bullet">
                <% school_day.lectures.each do |lecture| %>
                  <li><%= link_to lecture.print_name, lecture %></li>
                <% end %>
                </ul>
              </td>
              <td>
                <ul class="no-bullet">
                <% school_day.todos.each do |todo| %>
                  <li><%= link_to todo.print_name, todo %></li>
                <% end %>
                </ul>
              </td>
              <td>
                <ul class="no-bullet">
                <% if school_day.potd %>
                  <li><%= link_to school_day.potd.name, school_day.potd %></li>
                <% end %>
                </ul>
              </td>
              <td>
                <ul class="no-bullet">
                <% school_day.labs.each do |lab| %>
                  <li><%= link_to lab.print_name, lab %></li>
                <% end %>
                </ul>
              </td>
              <td>
                <ul class="no-bullet">
                <% school_day.links.each do |link| %>
                  <li><%= link_to link.print_name, link %></li>
                <% end %>
                </ul>
              </td>
              <td>
                <ul class="no-bullet">
                <% school_day.homeworks.each do |homework| %>
                  <li><%= link_to homework.print_name, homework %></li>
                <% end %>
                </ul>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>

    </div>  
  </div>
</div>

<br />
              