config/routes.rb
Pizza::Application.routes.draw do
  
  # get "password_resets/new"

  # get  'signup', to: 'users#new',        as: 'signup'
  
  get  'login',  to: 'sessions#new',     as: 'login'
  post 'login',  to: 'sessions#create',  as: 'login'
  get  'logout', to: 'sessions#destroy', as: 'logout'
  get  'sessions', to: 'sessions#index', as: 'sessions'
  post 'sessions', to: 'sessions#create'
  # resources :sessions
  
  resources :users, except: [:new]
  resources :password_resets

  get 'weeks',     to: 'weeks#index', as: 'weeks'
  get 'weeks/:id', to: 'weeks#show',  as: 'week'

  get    'unread', to: 'notifications#index',   as: 'notifications'
  delete 'unread', to: 'notifications#destroy', as: 'notifications'

  get 'search', to: 'searches#index'
  resources :searches
  
  post 'announcements/markallread', to: 'announcements#markallread', as: 'mark_all_read'
  resources :announcements, except: [:show, :new, :edit]


  resources :school_days do
    resources :comments
  end


  resources :lectures do
    resources :comments
  end
  get 'lectures/new/preview',      to: 'lectures#new_preview',  as: 'new_lecture_preview'
  get 'lectures/:id/preview',      to: 'lectures#preview',      as: 'lecture_preview'
  get 'lectures/:id/edit/preview', to: 'lectures#edit_preview', as: 'edit_lecture_preview'


  resources :todos do
    resources :comments
  end
  get 'todos/new/preview',      to: 'todos#new_preview',  as: 'new_todo_preview'
  get 'todos/:id/preview',      to: 'todos#preview',      as: 'todo_preview'
  get 'todos/:id/edit/preview', to: 'todos#edit_preview', as: 'edit_todo_preview'
  

  resources :potds do
    resources :comments
  end
  get 'potds/new/preview',      to: 'potds#new_preview',  as: 'new_potd_preview'
  get 'potds/:id/preview',      to: 'potds#preview',      as: 'potd_preview'
  get 'potds/:id/edit/preview', to: 'potds#edit_preview', as: 'edit_potd_preview'


  resources :labs do
    resources :comments
  end
  get 'labs/new/preview',      to: 'labs#new_preview',  as: 'new_lab_preview'
  get 'labs/:id/preview',      to: 'labs#preview',      as: 'lab_preview'
  get 'labs/:id/edit/preview', to: 'labs#edit_preview', as: 'edit_lab_preview'


  resources :links do
    resources :comments
  end
  get 'links/new/preview',      to: 'links#new_preview',  as: 'new_link_preview'
  get 'links/:id/preview',      to: 'links#preview',      as: 'link_preview'
  get 'links/:id/edit/preview', to: 'links#edit_preview', as: 'edit_link_preview'


  resources :homeworks do
    resources :comments
  end
  get 'homeworks/new/preview',      to: 'homeworks#new_preview',  as: 'new_homework_preview'
  get 'homeworks/:id/preview',      to: 'homeworks#preview',      as: 'homework_preview'
  get 'homeworks/:id/edit/preview', to: 'homeworks#edit_preview', as: 'edit_homework_preview'
  

  resources :comments, only: [:index, :create, :update, :destroy]
  get 'discussion', to: 'comments#index', as: 'discussion'

  resources :attachments

  root :to => 'passthrough#index'

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  include Formattable
  acts_as_readable :on => :created_at
  
  attr_accessible :content, :creator, :file_upload, :title
  attr_accessible :school_day_ids, :attachment_ids, :comment_ids, :attachments_attributes   # these columns do not exist in db - only for mass assign

  has_many :school_day_lectures
  has_many :school_days, :through => :school_day_lectures

  has_many :attachments, as: :attachable
  has_many :comments, as: :commentable, :dependent => :destroy

  accepts_nested_attributes_for :attachments, allow_destroy: true

  validates_uniqueness_of :title, :case_sensitive => false
  validates :title, :presence => true
  validates :content, :presence => true

  searchable do
    text :title, :content, :creator, :file_upload  
  end

  def print_name
    title
  end

  def print_search
    [title, content, creator, file_upload]
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  
  load_and_authorize_resource

  # GET /lectures
  # GET /lectures.json
  def index
    if request.referrer.split('/').last == "preview"
      @deleted_from_preview = true
    end
    
    @lectures = Lecture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lectures }
    end
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    @lecture = Lecture.find(params[:id])
    @from_preview = false

    @commentable = @lecture
    @comments = @commentable.comments
    @comment = Comment.new

    @lecture.mark_as_read! :for => current_user
    @lecture.comments.each do |comment|
      comment.mark_as_read! :for => current_user
    end

    @active_school_day = most_recent_day_for_material(@lecture)
    load_prev_and_next_day

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lecture }
    end
  end

  def preview
    @lecture = Lecture.find(params[:id])
    @from_preview = true
    render "show_preview", :layout => "preview"
  end

  # GET /lectures/new
  # GET /lectures/new.json
  def new
    @lecture = Lecture.new
    @active_school_day = SchoolDay.find(params[:day]) unless params[:day].nil? || params[:day].empty?
    load_prev_and_next_day

    # @attachment = @lecture.attachments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lecture }
    end
  end

  def new_preview
    @lecture = Lecture.new
    @from_preview = true
    render "form_preview", :layout => "preview"
  end

  # GET /lectures/1/edit
  def edit
    @lecture = Lecture.find(params[:id])

    @attachments = @lecture.attachments
    # @attachment  = @lecture.attachments.build
    
    @lecture.mark_as_read! :for => current_user

    @active_school_day = most_recent_day_for_material(@lecture)
    load_prev_and_next_day
  end

  def edit_preview
    @lecture = Lecture.find(params[:id])
    @from_preview = true
    render "form_preview", :layout => "preview"
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(params[:lecture])

    respond_to do |format|
      if @lecture.save
        if params[:day].nil?
          format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
          format.json { render json: @lecture, status: :created, location: @lecture }
        elsif params[:day].empty?
          format.html { redirect_to new_school_day_path + "?lecture_added=#{@lecture.id}#lectures", notice: 'Lecture was successfully created.' }
        else
          format.html { redirect_to edit_school_day_path(SchoolDay.find(params[:day])) + "?lecture_added=#{@lecture.id}#lectures", notice: 'Lecture was successfully created.' }
        end
      else
        if request.referrer.split('/').last == "preview"
          @from_preview = true
          format.html { render "form_preview", :layout => "preview" }
          format.json { render json: @lecture.errors, status: :unprocessable_entity }
        else
          format.html { render action: "new", :locals => {:day => params[:day]} }
          format.json { render json: @lecture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /lectures/1
  # PUT /lectures/1.json
  def update
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      if @lecture.update_attributes(params[:lecture])
        if request.referrer.split('/').last == "preview"
          format.html { redirect_to lecture_preview_path(@lecture), notice: 'Lecture was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
          format.json { head :no_content }
        end
      else
        if request.referrer.split('/').last == "preview"
          @from_preview = true
          format.html { render "form_preview", :layout => "preview" }
          format.json { render json: @lecture.errors, status: :unprocessable_entity }
        else
          format.html { render action: "edit" }
          format.json { render json: @lecture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture = Lecture.find(params[:id])
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to lectures_url, notice: "Lecture was successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_body_index_content.html.erb
<td>
  <%= simple_format(re_truncate material.content, length: 500) %>
</td>

<td>
  <ul class="no-bullet">
  <% material.attachments.each do |attachment| %>
    <li>
      <%= link_to attachment.title, attachment.filename.to_s %>
    </li>
  <% end %>
  </ul>
</td>

app/views/lectures/_body_show.erb
<div class="span9 maxspan minspan">
  <div class="widget wlightblue mainwidget">
    <div class="widget-head">
      <div class="pull-left">Lecture</div>
      <div class="widget-icons pull-right">
        <% if can? :edit, @lecture %>
          <% path = @from_preview ? edit_lecture_preview_path : edit_lecture_path %>
          <span class="admin"><a href="<%= path %>"><i class="icon-pencil"></i></a></span>
        <% end %>

        <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
        <!-- <a href="#" class="wclose"><i class="icon-remove"></i></a> -->
      </div>
      <div class="clearfix"></div>
    </div>

    <div class="widget-content">
      <div class="padd lowtop">

        <p>
          <h3><strong><%= @lecture.print_name %></strong></h3>
        </p>    

        <div class="spaced-paragraphs">
          <%= auto_link(better_format(@lecture.content), :all, :target => "_blank") %>
        </div>

        <br />
        <p>
          <h4>Attached Files:</h4>
          <ol>
          <% @lecture.attachments.each do |attachment| %>
            <li>
              <%= link_to attachment.title, attachment.filename.to_s %>
            </li>
          <% end %>
          </ol>
        </p>

      </div>
    </div>
  </div>
</div>

app/views/lectures/_form.html.erb
<%= form_for @lecture, :html => {class: "form-horizontal"} do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:day] %>
    <div class="field">
      <%= hidden_field_tag :day, params[:day] %>
    </div>
  <% end %> 

  <% if current_user %>
    <div class="field">
      <%= f.hidden_field :creator, :value => current_user.id %>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label :title, "Title #{mark_required(@lecture, :title)}", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :content, "Content #{mark_required(@lecture, :content)}", class: "control-label" %>
    <div class="controls">
      <%= f.text_area :content %>
    </div>
  </div>
  
  <!-- Sub-widget -->
  <div class="widget form-sub-widget hoverable nested-add-remove">
    <div class="widget-head">
      <div class="pull-left">Attachments</div>
      <div class="widget-icons pull-right">
        <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
      </div>
      <div class="clearfix"></div>
    </div>

    <div class="widget-content">
      <div class="padd">

        <!-- <div class="control-group">
          <%# f.label :attachment, "Select Existing Attachment(s):", class: "control-label" %> 
          <div class="controls">
            <%# f.collection_select(:attachment_ids, Attachment.order("title"), :id, :title, {:selected => @lecture.attachment_ids, :prompt => "Please Select Attachment(s)"}, {:class => "span4 inline", multiple: "multiple", size: 8}) %>
          </div>
            <%# link_to "Create New", new_attachment_path, target: "_blank", class: "btn btn-primary link-btn new-material control-label" %>
        </div> -->

        <%= f.fields_for :attachments do |builder| %>
          <%= render 'layouts/attachment_fields', f: builder %>
        <% end %>

        <%= link_to_add_fields "Add Attachment", f, :attachments, "btn btn-primary link-btn" %>

      </div>
    </div>
  </div>
  <!-- End Sub-widget -->

  <div class="control-group">
    <%= f.label :school_day, "Select Day(s)", class: "control-label" %>
    <div class="controls">
      <% selected_ids = @lecture.school_day_ids %>
      <% selected_ids << params[:day] %>
      <%= f.collection_select(:school_day_ids, SchoolDay.order("ordinal DESC"), :id, :ordinal, {:selected => selected_ids, :prompt => "Please Select Day(s)"}, {:class => "span4 multi-select", multiple: "multiple", size: 10}) %>
    </div>
  </div>
  
  <div class="actions inline">
    <%= f.submit "Submit", class: "btn btn-info" %>
  </div>
  
  <%= link_to "Cancel", cancel_path_for(@lecture), class: "btn btn-inverse link-btn" %>

  <% if @lecture.persisted? %>
    <%= link_to "Delete", @lecture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger link-btn" %>
  <% end %>
<% end %>

app/views/lectures/edit.html.erb
<%= render partial: "layouts/header_materials_edit", locals: {active_school_day: @school_day, previous_school_day: @previous_school_day, next_school_day: @next_school_day, material: @lecture} %>

<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>
    
    <div class="row-fluid fit-content">

      <div class="span9 maxspan minspan">
        <div class="widget wlightblue mainwidget">
          <div class="widget-head">
            <div class="pull-left">Editing Lecture</div>
            <div class="widget-icons pull-right">
              <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
              <!-- <a href="#" class="wclose"><i class="icon-remove"></i></a> -->
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="widget-content">
            <div class="padd lowtop">

              <%= render 'form' %>

						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
</div>

app/views/lectures/form_preview.html.erb
<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>
    
    <div class="row-fluid fit-content">

      <div class="span9 maxspan minspan">
        <div class="widget wlightblue mainwidget">
          <div class="widget-head">
            <div class="pull-left">
              <% action = @lecture.persisted? ? "Editing" : "New" %>
              <%= "#{action} Lecture" %>
            </div>
            <div class="widget-icons pull-right">
              <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
              <!-- <a href="#" class="wclose"><i class="icon-remove"></i></a> -->
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="widget-content">
            <div class="padd lowtop">

              <%= render 'form' %>

            </div>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/lectures/index.html.erb
<%= render partial: "layouts/header_index", locals: {chosen_materials: @lectures} %>

<% @material_columns = [{name: "Content", data_type: "data-sort=string"},{name: "Attachments"}] %>

<%= render partial: "layouts/body_materials_index", locals: {materials: @lectures, material_columns: @material_columns } %>

<% if @deleted_from_preview %>
  <script>
    parent.hideFrameAndReload();
  </script>
<% end %>

app/views/lectures/new.html.erb
<%= render partial: "layouts/header_new", locals: {new_material: @lecture} %>

<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>
    
    <div class="row-fluid fit-content">

      <div class="span9 maxspan minspan">
        <div class="widget wlightblue mainwidget">
          <div class="widget-head">
            <div class="pull-left">New Lecture</div>
            <div class="widget-icons pull-right">
              <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
              <!-- <a href="#" class="wclose"><i class="icon-remove"></i></a> -->
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="widget-content">
            <div class="padd lowtop">

              <%= render 'form' %>

            </div>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/lectures/show.html.erb
<%= render partial: "layouts/header_materials_show", locals: {material: @lecture} %>

<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>
    
    <div class="row-fluid fit-content">

      <%= render "body_show" %>

    </div>
    
    <%= render partial: "layouts/footer_materials_show", locals: {material: @lecture} %>

  </div>
</div>

app/views/lectures/show_preview.html.erb
<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>

    <div class="row-fluid fit-content">

      <%= render "body_show" %>

    </div>

  </div>
</div>