config/routes.rb
Pizza::Application.routes.draw do
  
  # get "password_resets/new"

  # get  'signup', to: 'users#new',        as: 'signup'
  
  get  'login',  to: 'sessions#new',     as: 'login'
  post 'login',  to: 'sessions#create',  as: 'login'
  get  'logout', to: 'sessions#destroy', as: 'logout'
  get  'sessions', to: 'sessions#index', as: 'sessions'
  post 'sessions', to: 'sessions#create'
  # resources :sessions
  
  resources :users, except: [:new]
  resources :password_resets

  get 'weeks',     to: 'weeks#index', as: 'weeks'
  get 'weeks/:id', to: 'weeks#show',  as: 'week'

  get    'unread', to: 'notifications#index',   as: 'notifications'
  delete 'unread', to: 'notifications#destroy', as: 'notifications'

  get 'search', to: 'searches#index'
  resources :searches
  
  post 'announcements/markallread', to: 'announcements#markallread', as: 'mark_all_read'
  resources :announcements, except: [:show, :new, :edit]


  resources :school_days do
    resources :comments
  end


  resources :lectures do
    resources :comments
  end
  get 'lectures/new/preview',      to: 'lectures#new_preview',  as: 'new_lecture_preview'
  get 'lectures/:id/preview',      to: 'lectures#preview',      as: 'lecture_preview'
  get 'lectures/:id/edit/preview', to: 'lectures#edit_preview', as: 'edit_lecture_preview'


  resources :todos do
    resources :comments
  end
  get 'todos/new/preview',      to: 'todos#new_preview',  as: 'new_todo_preview'
  get 'todos/:id/preview',      to: 'todos#preview',      as: 'todo_preview'
  get 'todos/:id/edit/preview', to: 'todos#edit_preview', as: 'edit_todo_preview'
  

  resources :potds do
    resources :comments
  end
  get 'potds/new/preview',      to: 'potds#new_preview',  as: 'new_potd_preview'
  get 'potds/:id/preview',      to: 'potds#preview',      as: 'potd_preview'
  get 'potds/:id/edit/preview', to: 'potds#edit_preview', as: 'edit_potd_preview'


  resources :labs do
    resources :comments
  end
  get 'labs/new/preview',      to: 'labs#new_preview',  as: 'new_lab_preview'
  get 'labs/:id/preview',      to: 'labs#preview',      as: 'lab_preview'
  get 'labs/:id/edit/preview', to: 'labs#edit_preview', as: 'edit_lab_preview'


  resources :links do
    resources :comments
  end
  get 'links/new/preview',      to: 'links#new_preview',  as: 'new_link_preview'
  get 'links/:id/preview',      to: 'links#preview',      as: 'link_preview'
  get 'links/:id/edit/preview', to: 'links#edit_preview', as: 'edit_link_preview'


  resources :homeworks do
    resources :comments
  end
  get 'homeworks/new/preview',      to: 'homeworks#new_preview',  as: 'new_homework_preview'
  get 'homeworks/:id/preview',      to: 'homeworks#preview',      as: 'homework_preview'
  get 'homeworks/:id/edit/preview', to: 'homeworks#edit_preview', as: 'edit_homework_preview'
  

  resources :comments, only: [:index, :create, :update, :destroy]
  get 'discussion', to: 'comments#index', as: 'discussion'

  resources :attachments

  root :to => 'passthrough#index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  before_save :set_title_before_save

  # attr_accessor :title
  attr_accessible :attachable_id, :attachable_type, :filename, :title

  belongs_to :lecture
  belongs_to :attachable, polymorphic: true

  mount_uploader :filename, FileUploader

  validates :filename, :presence => true

  searchable do
    text :attachable_type, :filename, :title  
  end

  def print_name
  	title
  end

  def print_search
    [title, filename, attachable_type]
  end

  def filename_short
    filename.to_s.split("/").last
  end

  def set_title_before_save
    if self.title.nil? || self.title.empty? || self.title =~ /\A\s+\z/ || filename_changed?
      self.title = filename_short # 'title = ' doesnt work, need 'self.title = '
    end
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  
  load_and_authorize_resource

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url, notice: "Attachment was successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= render "layouts/messages" %>

<% action = @attachment.filename ? "Replace" : "Add" %>

<%= form_for @attachment, :html => {class: "form-inline"} do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, "Title #{mark_required(@attachment, :title)} <em>(leave blank to use filename as title)</em>".html_safe %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <%= f.label :filename, "Current File#{mark_required(@attachment, :filename)} :" %> 
  <strong><%= @attachment.filename_short || "None" %></strong>
  <br>
  
  <div class="control-group">
    <%= f.label :filename, "#{action} File:" %>
    <div class="controls">
      <%= f.file_field :filename %>
    </div>
  </div>

  <div class="actions inline">
    <%= f.submit "Submit", class: "btn btn-info" %>
  </div>

  <%= link_to "Cancel", cancel_path_for(@attachment), class: "btn btn-inverse link-btn" %>

  <% if @attachment.persisted? %>
    <%= link_to "Delete", @attachment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger link-btn" %>
  <% end %>
<% end %>

app/views/attachments/edit.html.erb
<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>
    
    <div class="row-fluid fit-content">

      <div class="span9 maxspan minspan">
        <div class="widget wlightblue mainwidget">
          <div class="widget-head">
            <div class="pull-left">Editing Attachment</div>
            <div class="widget-icons pull-right">
              <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
              <!-- <a href="#" class="wclose"><i class="icon-remove"></i></a> -->
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="widget-content">
            <div class="padd lowtop">

              <%= render 'form' %>

            </div>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/attachments/index.html.erb
<div class="page-head">
  <% title "All Attachments" %>
  <h2 class="inline"><%= yield(:title) %></h2>
  
  <ul class="horizontal-list breadcrumb">
    <li>Show All: </li>
    <% material_type_list.each do |material_type_hash| %>
      <% material_type = material_type_hash[:name] %>
      <% material_icon = material_type_hash[:icon] %>
      <% material_types  = material_type.pluralize %>
      <% material_title  = material_capitalize(material_type) %>
      <% material_titles = material_title.pluralize %>
      
      <%# unless material_type == chosen_material_type %>
      <li>
        <a href="<%= self.send("#{material_types}_path") %>">
          <i class="icon-<%= material_icon %>"></i>
          <%= material_titles %>
        </a>
      </li>
      <%# end %>
      
    <% end %>
  </ul>

  <br />

  <% if can? :edit, @attachments %>
    <%= link_to "Create New Attachment", new_attachment_path, class: "btn btn-primary link-btn" %>
  <% end %>

</div>

<div class="matter">
  <div class="container-fluid">
    <%= render "layouts/messages" %>
    <div class="row-fluid">
      <div class="span12 table-maxspan minspan">

        <table class="table table-hover" id="linksTable">
          <thead>
            <tr>
              <th data-sort="string">Title</th>
              <th data-sort="string">Filename</th>
              <th data-sort="date">Last Updated</th>
              <th data-sort="date">Created</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          
          <tbody>
          <% @attachments.each do |attachment| %>
            <tr>
              <td><%= link_to attachment.title, attachment %></td>
              <td><%= link_to attachment.filename_short, attachment.filename.to_s %></td>
              <td><%= attachment.updated_at.strftime("%b %d, %Y %l:%M%P") %></td>
              <td><%= attachment.updated_at.strftime("%b %d, %Y %l:%M%P") %></td>
              <td><%= link_to 'Show', attachment %></td>
              <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
              <td><%= link_to 'Delete', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>

    </div>
  </div>
</div>

app/views/attachments/new.html.erb
<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>
    
    <div class="row-fluid fit-content">

      <div class="span9 maxspan minspan">
        <div class="widget wlightblue mainwidget">
          <div class="widget-head">
            <div class="pull-left">New Attachment</div>
            <div class="widget-icons pull-right">
              <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
              <!-- <a href="#" class="wclose"><i class="icon-remove"></i></a> -->
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="widget-content">
            <div class="padd lowtop">

              <%= render 'form' %>

            </div>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/attachments/show.html.erb
<div class="matter">
  <div class="container-fluid">

    <%= render "layouts/messages" %>
    
    <div class="row-fluid fit-content">

      <div class="span9 maxspan minspan">
        <div class="widget wlightblue mainwidget">
          <div class="widget-head">
            <div class="pull-left">Attachment</div>
            <div class="widget-icons pull-right">
                <span class="admin"><a href="<%= edit_attachment_path %>"><i class="icon-pencil"></i></a></span>
              <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
              <!-- <a href="#" class="wclose"><i class="icon-remove"></i></a> -->
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="widget-content">
            <div class="padd lowtop">
              <h4><%= @attachment.title %></h4>
              <br>
              <b>File:</b>
                <%= link_to @attachment.filename_short, @attachment.filename.to_s %>
              <br><br>
              <b>Belongs to:</b>
                <p>
                <% if @attachment.attachable_type.nil? %>
                  No materials selected!
                <% else %>
                  <% material = Lecture.find(@attachment.attachable_id) if @attachment.attachable_type == "Lecture" %>
                  <% material_type = @attachment.attachable_type.underscore %>
                  <%= material_capitalize(material_type) %>:
                  <%= link_to "#{material.print_name}", self.send("#{material_type}_path", material) %>
                <% end %>
                </p>
            </div>
          </div>
        </div>

        <% if can? :edit, @active_school_day %>
        <span class="admin">
          <%= link_to 'Edit',   edit_attachment_path(@attachment) %> |
          <%= link_to 'Delete', @attachment, method: :delete, data: { confirm: 'Are you sure?' }  %> |
        </span>
        <% end %>
        <%= link_to "Show All Attachments", attachments_path %>
      </div>

    </div>
    
  </div>
</div>