config/routes.rb
Pizza::Application.routes.draw do
  
  # get "password_resets/new"

  # get  'signup', to: 'users#new',        as: 'signup'
  
  get  'login',  to: 'sessions#new',     as: 'login'
  post 'login',  to: 'sessions#create',  as: 'login'
  get  'logout', to: 'sessions#destroy', as: 'logout'
  get  'sessions', to: 'sessions#index', as: 'sessions'
  post 'sessions', to: 'sessions#create'
  # resources :sessions
  
  resources :users, except: [:new]
  resources :password_resets

  get 'weeks',     to: 'weeks#index', as: 'weeks'
  get 'weeks/:id', to: 'weeks#show',  as: 'week'

  get    'unread', to: 'notifications#index',   as: 'notifications'
  delete 'unread', to: 'notifications#destroy', as: 'notifications'

  get 'search', to: 'searches#index'
  resources :searches
  
  post 'announcements/markallread', to: 'announcements#markallread', as: 'mark_all_read'
  resources :announcements, except: [:show, :new, :edit]


  resources :school_days do
    resources :comments
  end


  resources :lectures do
    resources :comments
  end
  get 'lectures/new/preview',      to: 'lectures#new_preview',  as: 'new_lecture_preview'
  get 'lectures/:id/preview',      to: 'lectures#preview',      as: 'lecture_preview'
  get 'lectures/:id/edit/preview', to: 'lectures#edit_preview', as: 'edit_lecture_preview'


  resources :todos do
    resources :comments
  end
  get 'todos/new/preview',      to: 'todos#new_preview',  as: 'new_todo_preview'
  get 'todos/:id/preview',      to: 'todos#preview',      as: 'todo_preview'
  get 'todos/:id/edit/preview', to: 'todos#edit_preview', as: 'edit_todo_preview'
  

  resources :potds do
    resources :comments
  end
  get 'potds/new/preview',      to: 'potds#new_preview',  as: 'new_potd_preview'
  get 'potds/:id/preview',      to: 'potds#preview',      as: 'potd_preview'
  get 'potds/:id/edit/preview', to: 'potds#edit_preview', as: 'edit_potd_preview'


  resources :labs do
    resources :comments
  end
  get 'labs/new/preview',      to: 'labs#new_preview',  as: 'new_lab_preview'
  get 'labs/:id/preview',      to: 'labs#preview',      as: 'lab_preview'
  get 'labs/:id/edit/preview', to: 'labs#edit_preview', as: 'edit_lab_preview'


  resources :links do
    resources :comments
  end
  get 'links/new/preview',      to: 'links#new_preview',  as: 'new_link_preview'
  get 'links/:id/preview',      to: 'links#preview',      as: 'link_preview'
  get 'links/:id/edit/preview', to: 'links#edit_preview', as: 'edit_link_preview'


  resources :homeworks do
    resources :comments
  end
  get 'homeworks/new/preview',      to: 'homeworks#new_preview',  as: 'new_homework_preview'
  get 'homeworks/:id/preview',      to: 'homeworks#preview',      as: 'homework_preview'
  get 'homeworks/:id/edit/preview', to: 'homeworks#edit_preview', as: 'edit_homework_preview'
  

  resources :comments, only: [:index, :create, :update, :destroy]
  get 'discussion', to: 'comments#index', as: 'discussion'

  resources :attachments

  root :to => 'passthrough#index'

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @search = Sunspot.search(SchoolDay, Lecture, Lab, Todo, Homework, Potd, Link, Comment, Announcement) do
      fulltext params[:search]
      #paginate :per_page => 10
    end
    @searches = @search.results
    @query = params[:search]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<div class="page-head">
  <h2>All Results for "<%= @query %>"</h2>
</div>

<div class="matter">
  <div class="container-fluid">
    <div class="row-fluid">
      <ol>
        <%#  debugger %>
        <% if @searches.empty? %>
          No Results Found
        <% else %>
          <h3> <%= pluralize(@searches.size,"Result")  %> </h3>
          <% @searches.each do |object| %>
            <li>
            	<% if object.class == SchoolDay %>
            		<a href=<%= "school_days/#{object.id}" %>><%="#{object.class}:"%> <%= object.print_name %></a>
                  <%= better_format(re_truncate(object.try(:print_search),{length:100}, 2)) %> 
            	<% else %>
              <%# debugger %>
                <% if object.class == Comment %>
                  <% comment_parent = object.commentable_type.classify.constantize.find(object.commentable_id) %>
                  <% comment_parent_type = object.commentable_type.underscore %>
                  <a href='<%= self.send("#{comment_parent_type}_path", comment_parent)+"#comment-#{object.id}" %>'><%="Comment for #{material_capitalize(comment_parent_type)} #{comment_parent.print_name}"  %></a>
                  <br> 
                  <%= re_truncate(object.try(:print_search),length:100) %>
                <% else %>
                  <a href=<%= "#{object.class.to_s.downcase}s/#{object.id}" %>><%= object.print_name %></a>
                  <br> 
                  <%= re_truncate(object.try(:print_search),length:100) %>
                <% end %>

            	<% end %>
            </li>
           <% end %>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>